[project]
name = "lab01-uv"
version = "0.1.0"
description = "Lab 1: robust miljÃ¶hantering med uv"
readme = "README.md"
requires-python = ">=3.10, <3.13"
dependencies = [
    "ipykernel",
    "jupyter",
    "pandas",
    "scikit-learn",
    "torch",
    "torchvision",
    "torchaudio",
]
